apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: foltz-io-cert
spec:
  secretName: foltz-io-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - foltz.io
