apiVersion: apps/v1
kind: Deployment
metadata:
  name: foltz-io
spec:
  selector:
    matchLabels:
      app: foltz-io
  replicas: 1
  template:
    metadata:
      labels:
        app: foltz-io
    spec:
      containers:
      - name: foltz-io
        image: foltik/foltz.io
        ports:
        - containerPort: 443
        volumeMounts:
        - name: cert
          mountPath: /etc/nginx/certs
          readOnly: true
      imagePullPolicy: Always
      volumes:
      - name: cert
        secret:
          secretName: foltz-io-cert
