apiVersion: v1
kind: Service
metadata:
  name: foltz-io
  labels:
    app: foltz-io
spec:
  ports:
  - port: 443
    protocol: TCP
  selector:
    app: foltz-io
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foltz-io-gateway
spec:
  selector:
    tier: external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - foltz.io
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - foltz.io
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foltz-io
spec:
  hosts:
  - foltz.io
  gateways:
  - foltz-io-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - foltz.io
    route:
    - destination:
        host: foltz-io
        port:
          number: 443
  http: 
  - match:
    - uri:
        prefix: '/'
    route:
    - destination:
        host: foltz-io
